---
abstract: "Parse Industry Canada \"Spectrum Direct\" radio frequency search output"
author:
  - "Dave O'Neill <dmo@dmo.ca>"
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.31
generated_by: 'Dist::Zilla version 2.101151'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Parse-SpectrumDirect-RadioFrequency
recommends: {}
requires:
  perl: 5.008
version: 0.101
